use crate::schema::commands; // refers to the schema file generated by diesel
use serde::Serialize; // makes object of this class json serializable, we will convert these objects to json and send to user.

#[derive(Queryable, Serialize, Debug)] // these annotation adds extra functionality to objects of this struct, Debug is for printing in console `dbg!(todo)`
pub struct Command {
    pub id: i32,
    pub key: String,
    pub name: String,
    pub description: String,
    pub icon: String,
    pub data: String,
    pub extension_id: String,
    pub extension_path: String,
}

#[derive(Insertable, Serialize, Debug, Clone)]
#[table_name = "commands"]
pub struct NewCommand<'a> {
    // this struct will be use when inserting into the db, a struct can be Queryable and Insertable at the same time too.
    pub key: &'a str,
    pub name: &'a str,
    pub description: &'a str,
    pub icon: &'a str,
    pub data: &'a str,
    pub extension_id: &'a str,
    pub extension_path: &'a str,
}
